name: Form.PasswordStrength
author: nak5ive
category: Forms
tags: [password, strength, entropy, forms]
docs: http://nak5ive.github.com/Form.PasswordStrength
demo: http://nak5ive.github.com/Form.PasswordStrength